---
title: "Past Projects"
output: 
  html_document:
      toc: true
      toc_float: true
---

## Growth-Fragmentation Models: Cell Growth and Division 

This is my final-year dissertation on models of cell growth and division. To briefly walk through the project, mitosis falls under a type of mathematical model called the growth-fragmentation model (GF model) where cells grow and fragment at random time points. The aim of my project was to test out empirical Markov Chain approaches  that aim to predict the **growth rate of cell count** and the **long-term distribution of cell sizes**. Putting this into context, suppose we are observing cancer cells, simulating the growth of a tumour with a GF model would help us gauge how aggressive that tumour is and this can be helpful when coming up with solutions for treating the disease. 
 
## Identifying Risk Factors of COVID-19 in the UK 

Data analysis and predictive modelling using social, demographic and economic data by the Office for National Statistics (UK)

This was a project I did during COVID, where I analyzed why some geographical areas in the UK had more deaths than others, as an effort to identify potential risk factors of COVID other than gender, ethnicity, pre-existing health conditions, etc. I used data published by the Office for National Statistics (ONS) that include almost 70 different variables such as occupation, social grade, public transport, and so on. I also conducted analysis on the complete data and come up with a model to predict the number of deaths in each geographical area for the portion of data that was unavailable. Our prediction model came top 8 out of 75 groups in class :'). 

## Optimizing Turnaround Time: How should airplanes by boarded and deboarded?

This project isn't as relevant as the previous two but I thought it might be fun to review! Essentially, we tested out 4 main methods to board and deboard passengers before a flight takes off and after it lands and compared which model was the most efficient. We did this by coding up a simulation in R. 
